[build]
  command = "npm run build"
  publish = "build"
  base = "client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://lyricfinder-production.up.railway.app/api/:splat"  # Replace with your actual Railway URL
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
